services:
  - type: web
    name: precision-oncology-backend
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python main.py"
    healthCheckPath: "/api/v1/models"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: ADMIN_SIGNUP_CODE
        value: ADMIN-SECRET-2026
      - key: ADMIN_APPROVAL_CODE
        value: PREC-ONCO-2026
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
      - key: MALLOC_TRIM_THRESHOLD_
        value: "65536"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"

